### ISSUE TITLE
about bmp bootloader

### ISSUE THREAD

**Issue by Xavier1989** [joric/bmpapi#1]
Hi！I use the bmp bootloader with a custom keyboard which designed by myself. The layout is 75%. As i know, you have some interest in make the bootloader open source. Maybe i can provide some help.

**Comment by joric** [comment]
Please do tell. How did you upload it? Are pins the same as on BMP? Does it use the same module?

**Comment by Xavier1989** [comment]
My hardware that base on nRF52840 is different from that module. So some pins is different too. If you are familiar with development about this chip, you will know how to do. Give me your personal contact information so that I can tell you more if you want.

**Comment by joric** [comment]
Well, use iamjoric gmail then.

**Comment by joric** [comment]
@Xavier1989 are you still here? Where did you go? I haven't received any emails from you so far.
